profile = "prof" # AWS profile
cluster = "prof-ite" # name of ECS cluster
task_definition = "prof-ite-app" # name of the task definition
container_name = "app" # name of the container

log_group = "ecs-tool"

[deploy]
services = ["app", "tasks"]

[ssh]
shell = "bash"
service = "app"
container_name = "app"
instance_user = "ec2-user"

[run]
service = "app" # Name of service to run one off task in
launch_type = "EC2" # FARGATE if the task_definition requires FARGATE
